plugins {
    id 'java'
    id 'application'
}

group = 'training.gradle'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.commons:commons-lang3:3.14.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

application {
    mainClass = 'training.gradle.App'
}

tasks.named('test') {
    useJUnitPlatform()
}